# Generated by Django 4.1 on 2023-01-04 20:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Pedidos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sabor",
                    models.CharField(
                        choices=[
                            ("Chocolate", "chocolate"),
                            ("Vainilla", "vainilla"),
                            ("Confetti", "confetti"),
                        ],
                        max_length=20,
                    ),
                ),
                ("persona", models.CharField(max_length=208)),
                (
                    "fecha_pedido",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("fecha_entrega", models.DateTimeField()),
                ("direccion", models.CharField(max_length=200)),
                ("direccion_URL", models.URLField()),
                ("detalles", models.TextField(blank=True, null=True)),
            ],
        ),
    ]
