# Generated by Django 4.1 on 2023-01-06 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Cakes", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pedidos",
            name="direccion_URL",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="pedidos",
            name="sabor",
            field=models.CharField(
                choices=[
                    ("Chocolate", "chocolate"),
                    ("Vainilla", "vainilla"),
                    ("Confetti", "confetti"),
                ],
                max_length=208,
            ),
        ),
    ]
