# Generated by Django 4.1 on 2023-01-06 19:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("Cakes", "0002_alter_pedidos_direccion_url_alter_pedidos_sabor"),
    ]

    operations = [
        migrations.CreateModel(
            name="Pedidos1",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sabor",
                    models.CharField(
                        choices=[
                            ("Chocolate", "chocolate"),
                            ("Vainilla", "vainilla"),
                            ("Confetti", "confetti"),
                        ],
                        max_length=208,
                    ),
                ),
                ("persona", models.CharField(max_length=208)),
                (
                    "fecha_pedido",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("fecha_entrega", models.DateTimeField()),
                ("direccion", models.CharField(max_length=200)),
                ("direccion_URL", models.URLField(blank=True, null=True)),
                ("detalles", models.TextField(blank=True, null=True)),
            ],
        ),
    ]
