# Generated by Django 4.1 on 2023-01-06 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Cakes", "0003_pedidos1"),
    ]

    operations = [
        migrations.DeleteModel(name="Pedidos1",),
    ]
