# Generated by Django 4.1 on 2023-01-06 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Cakes", "0004_delete_pedidos1"),
    ]

    operations = [
        migrations.AddField(
            model_name="pedidos",
            name="entre",
            field=models.BooleanField(default=False),
        ),
    ]
