# Generated by Django 4.1 on 2023-01-07 00:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("Cakes", "0005_pedidos_entre"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pedidos", name="fecha_entrega", field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="pedidos",
            name="fecha_pedido",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
